---
title: "Thesis Work"
author: Noah Edwards-Thro
output: github_document
---

```{r}
library(tidyverse)
library(nbastatR)
library(mclust)
Sys.setenv("VROOM_CONNECTION_SIZE" = 131072*2)
```

```{r}
bref_stats<-bref_players_stats(seasons = 2009:2018, tables = c("totals", "per_game", "advanced", "per_minute", "per_poss"))
```

```{r}
Shooting_Scrape <- read_csv("Basketball Reference Scrape.csv")
```

```{r}
Shooting_Scrape <- Shooting_Scrape %>%
  separate(Player, c("Player_Name", "Player_ID"), sep = "\\\\")
```

```{r}
Shooting_Scrape$yearSeason<-as.double(Shooting_Scrape$Year%>%
  str_extract(pattern = "[^-]+$"))
```

```{r}
Shooting_Scrape<-Shooting_Scrape%>%group_by(Player, Age)%>%filter(G == max(G))
```

# Evaluate if we have the correct number of players)
```{r}
not_traded<-bref_stats%>%filter(slugTeamBREF != "TOT")
traded<-bref_stats%>%filter(slugTeamBREF == "TOT")
traded_twice <- traded%>%filter(nchar(slugTeamsBREF) >9)
traded_thrice<-traded_twice%>%filter(nchar(slugTeamsBREF) > 15)
Count_Games<-bref_stats%>%filter(countGames > 30)
Filter1<-game_data%>%filter(gp>30)
```

### Density Chart
```{r}
plot1<-ggplot(Shooting_Scrape, aes(x = G))+
  geom_density()
plot2<-ggplot(bref_stats, aes(x = countGames))+
  geom_density()
plot1
```

```{r}
master<-inner_join(bref_stats, Shooting_Scrape, by = c("yearSeason" = "yearSeason", "slugPlayerBREF" = "Player_ID"))
nums <- unlist(lapply(master, is.numeric))
master2<-master[nums]
master3<-master2[order]
master4<-master3%>%na.omit()
```


```{r}
order<-c(54,55,57,58,59,60,47,61,50,53,9,73,101,106,107,100,111,108,109,96,97,98,99)
```

```{r}
BIC<-mclustBIC(master4)
Mclust(master4)
```

